<?php 
$your_email ='brianadeluccia@gmail.com';// <<=== update to your email address

session_start();
$errors = '';
$fname = '';
$email = '';
$message = '';

if(isset($_POST['submit']))
{
	
	$fname = $_POST['fname'];
	$lname = $_POST['lname'];
	$phone = $_POST['phone'];
	$email = $_POST['email'];
	$message = $_POST['message'];
	///------------Do Validations-------------
	if(empty($fname)||empty($message))
	{
		$errors .= "\n Name and Message are required fields. ";	
	}
	if(IsInjected($email))
	{
		$errors .= "\n Bad email value!";
	}
	
	if(empty($errors))
	{
		//send the email
		$to = $your_email;
		$subject="New form submission - Do not reply";
		$from = "Website Contact Form";
		
		$body = "This is an automated email generated by your website form; please do not reply.\n".
		"\n".
		"Name: $fname $lname\n".
		"Phone: $phone\n".
		"Email: $email \n".
		"Message: \n ".
		"$message\n".	
		
		$headers .= "Reply-To: $email \r\n";
		
		mail($to, $subject, $body,$headers);
		
		echo "<script type='text/javascript'>alert('Thanks, your message has been recieved!'); window.location.href = 'index.php';</script>";
	}
}

// Function to validate against any email injection attempts
function IsInjected($str)
{
  $injections = array('(\n+)',
              '(\r+)',
              '(\t+)',
              '(%0A+)',
              '(%0D+)',
              '(%08+)',
              '(%09+)'
              );
  $inject = join('|', $injections);
  $inject = "/$inject/i";
  if(preg_match($inject,$str))
    {
    return true;
  }
  else
    {
    return false;
  }
}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Ana Luccia Website Design &amp; Development :: Online Marketing Solutions, Orange County, CA</title>
<meta name="keywords" content="website, web design, web development, user experience, marketing, logo design, logo creation, small businesses, local business, html, css, jquery, javascript, php, developer, orange county, california" />
<meta name="description" content="" />
<link href="css/style.css" rel="stylesheet" type="text/css" />
<link href="css/hover.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="js/nivo-slider.css" type="text/css" media="screen" />
<link rel="stylesheet" href="js/default/default.css" type="text/css" media="screen" />
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<link href='http://fonts.googleapis.com/css?family=Economica' rel='stylesheet' type='text/css'>
<script type="text/javascript" src="js/fancybox/jquery.fancybox.js?v=2.1.4"></script>
<link rel="stylesheet" type="text/css" href="js/fancybox/jquery.fancybox.css?v=2.1.4" media="screen" />
<script type='text/javascript' src='js/jquery.hoverIntent.minified.js'></script>
<script type="text/javascript" src="js/jquery.nivo.slider.js"></script>
<script type="text/javascript" src="js/gen_validatorv4.js"></script>
<script type="text/javascript" src="js/isotope.js"></script>
<script type="text/javascript">
$(window).load(function() {
        $('#slider').nivoSlider();
    });

$(window).load(function(){
    var $container = $('#container');
    $container.isotope({
        filter: '.home',
        animationOptions: {
            duration: 750,
            easing: 'linear',
            queue: false
        }
    });
 
    $('#nav a').click(function(){
        $('#nav .current').removeClass('current');
        $(this).addClass('current');
 
        var selector = $(this).attr('data-filter');
        $container.isotope({
            filter: selector,
            animationOptions: {
                duration: 750,
                easing: 'linear',
                queue: false
            }
         });
         return false;
    });
});

$(document).ready(function() {
			$('.group1').fancybox();
});
</script>

</head>
<body>
	<div id="wrap">
        <a href="" title="home"><img src="images/logo.png" alt="" /></a>
        <div id="nav">
            <ul>
                <li><a href="#" data-filter=".home" class="current">Home</a></li>
                <li><a href="#" data-filter=".about">About</a></li>
                <li><a href="#" data-filter=".portfolio">Portfolio</a></li>
                <li><a href="#" data-filter=".contact">Contact</a></li>
            </ul>
        </div>
        
        <div id="container">
            <div class="home">
            	<div id="slider-container">
                    	<div class="slider-wrapper theme-default">
            			<div id="slider" class="nivoSlider">
                        	<img src="images/slide3.jpg" alt="" />
                            <img src="images/slide1.jpg" alt="" />
                            <img src="images/slide2.jpg" alt="" />
                            <img src="images/slide4.jpg" alt="" />
                            <img src="images/slide5.jpg" alt="" />
                            <img src="images/slide6.jpg" alt="" />
                            <img src="images/slide7.jpg" alt="" />
                            <img src="images/slide8.jpg" alt="" />
                        </div>
                        </div>
                    </div>
                <div class="content">
                    <h1>Design &amp; Development</h1>
                    <p>Ana Luccia focuses on delivering elegant designs and a user-friendly experience through custom-tailored website solutions. Let me take your online presence to the next level, and leave your clients and visitors with that "wow" feeling that keeps them coming back for more.</p>
                </div>
            </div>
            
            <div class="about">
                <div class="content">
                    <h2>About Me</h2>
                    <p>With nearly 10 years experience delivering stunning custom website solutions, Ana Luccia has worked for boutique web shops and national marketing corporations alike, with plenty of freelance work in between. </p>
                    <p>"Having grown up as an aspiring sketch artist, my love affair with web design began with the realization that art could be transformed online into a functional and informative experience. I began experimenting with this new medium, which brought my eye for color and design and my obsession with the technical together at last. Everything clicked into place when I got my first gig with a local web shop.</p>
                    <p>I spent the next several years honing my HTML and CSS skills, and experimenting to find the most clean and efficient ways of writing code. Boring, right? Wrong! Transforming a new design into a working website is like working with a puzzle, only the box doesn't tell you how many pieces are inside. If you hate puzzles, that might be a little frustrating, but lucky for me, I kind of have a thing for them.</p>
                    <p>My passion is making you look good. Working with businesses to shape their online presence is one of the most rewarding experiences, and because each client has their own personal style, no two jobs are ever the same. If you're looking for a developer who can deliver that personal touch, you've come to the right place!"</p>
                 </div>
            </div>
            
            <div class="portfolio">
            	<div class="content">
                	<h2>Portfolio</h2>
                        <div class="container">
                        <div class="view">
                            <img src="images/feralfolk_s.jpg" alt="" />
                            <div class="mask">
                                <h2>Feral Folk Rescue</h2>
                                <a href="images/feralfolk.jpg" class="info group1" data-fancybox-group="gallery">View Design</a> 
                                <a href="http://www.feral-folk.com" class="info" target="_blank">View Website</a>
                            </div>
                        </div>
                        </div>
                        <div class="container">
                        <div class="view">
                            <img src="images/acp_s.jpg" alt="" />
                            <div class="mask">
                                <h2>American Car Prospector</h2>
                                <a href="images/acp.jpg" class="info group1" data-fancybox-group="gallery">View Design</a> 
                                <a href="http://www.americancarprospector.com" class="info" target="_blank">View Website</a>
                            </div>
                        </div>
                        </div>
                        <div class="container">
                        <div class="view">
                            <img src="images/hbremodel_s.jpg" alt="" />
                            <div class="mask">
                                <h2>HB Remodeler</h2>
                                <a href="images/hbremodel.jpg" class="info group1" data-fancybox-group="gallery">View Design</a> 
                                <a href="http://www.hbremodeler.com" class="info" target="_blank">View Website</a>
                            </div>
                        </div>
                        </div>
                    	<div class="container">
                        <div class="view">
                            <img src="images/sww_s.jpg" alt="" />
                            <div class="mask">
                                <h2>Sierra Western Wear</h2>
                                <a href="images/sww.jpg" class="info group1" data-fancybox-group="gallery">View Design</a> 
                                <a href="http://www.sierrawesternwear.com" class="info" target="_blank">View Website</a>
                            </div>
                        </div>
                        </div>
                        <div class="container">
                        <div class="view">
                            <img src="images/swwstore_s.jpg" alt="" />
                            <div class="mask">
                                <h2>Sierra Western Wear<br />Web Store </h2>
                                <a href="images/swwstore.jpg" class="info group1" data-fancybox-group="gallery">View Design</a> 
                                <a href="http://store.sierrawesternwear.com" class="info" target="_blank">View Website</a>
                            </div>
                        </div>
                        </div>
                        <div class="container">
                        <div class="view">
                            <img src="images/ed_s.jpg" alt="" />
                            <div class="mask">
                                <h2>E&amp;D Fence Co.</h2>
                                <a href="images/ed.jpg" class="info group1" data-fancybox-group="gallery">View Design</a> 
                                <a href="http://www.edfenceco.com" class="info" target="_blank">View Website</a>
                            </div>
                        </div>
                        </div>
                        <div class="container">
                        <div class="view">
                            <img src="images/bayview_s.jpg" alt="" />
                            <div class="mask">
                                <h2>Bayview Security</h2>
                                <a href="images/bayview.jpg" class="info group1" data-fancybox-group="gallery">View Design</a>
                            </div>
                        </div>
                        </div>
                        <div class="container">
                        <div class="view">
                            <img src="images/moore_s.jpg" alt="" />
                            <div class="mask">
                                <h2>Moore Air Inc.</h2>
                                <a href="images/moore.jpg" class="info group1" data-fancybox-group="gallery">View Design</a>
                                <a href="http://www.mooreairinc.com" class="info" target="_blank">View Website</a>
                            </div>
                        </div>
                        </div>
                        <div class="container">
                        <div class="view">
                            <img src="images/gl_s.jpg" alt="" />
                            <div class="mask">
                                <h2>Gordon Liebmann Family Attorneys</h2>
                                <a href="images/gl.jpg" class="info group1" data-fancybox-group="gallery">View Design</a>
                            </div>
                        </div>
                        </div>
                        <div class="container">
                        <div class="view">
                            <img src="images/pumpkin_s.jpg" alt="" />
                            <div class="mask">
                                <h2>Pumpkin Patch Preschool</h2>
                                <a href="images/pumpkin.jpg" class="info group1" data-fancybox-group="gallery">View Design</a>
                                <a href="http://www.pumpkinpatchpreschool.net" class="info" target="_blank">View Website</a>
                            </div>
                        </div>
                        </div>
                        <div class="container">
                        <div class="view">
                            <img src="images/king_s.jpg" alt="" />
                            <div class="mask">
                                <h2>King Lasik</h2>
                                <a href="images/king.jpg" class="info group1" data-fancybox-group="gallery">View Design</a>
                                <a href="http://www.kinglasikportlandmetro.com" class="info" target="_blank">View Website</a>
                            </div>
                        </div>
                        </div>
                        <div class="container">
                        <div class="view">
                            <img src="images/washington_s.jpg" alt="" />
                            <div class="mask">
                                <h2>Washington Fine Painting</h2>
                                <a href="images/washington.jpg" class="info group1" data-fancybox-group="gallery">View Design</a>
                            </div>
                        </div>
                        </div>
                        <div class="container">
                        <div class="view">
                            <img src="images/rlr_s.jpg" alt="" />
                            <div class="mask">
                                <h2>RLR Studios</h2>
                                <a href="images/rlr.jpg" class="info group1" data-fancybox-group="gallery">View Design</a> 
                                <a href="http://www.rlrstudios.com" class="info" target="_blank">View Website</a>
                            </div>
                        </div>
                        </div>
                        <div class="container">
                        <div class="view">
                            <img src="images/ko_s.jpg" alt="" />
                            <div class="mask">
                                <h2>KO Kreative Media</h2>
                                <a href="images/ko.jpg" class="info group1" data-fancybox-group="gallery">View Design</a>
                                <a href="http://www.kokreativemedia.com" class="info" target="_blank">View Website</a>
                            </div>
                        </div>
                        </div>
                        <div class="container">
                        <div class="view">
                            <img src="images/lincoln_s.jpg" alt="" />
                            <div class="mask">
                                <h2>Lincoln Pest Control</h2>
                                <a href="images/lincoln.jpg" class="info group1" data-fancybox-group="gallery">View Design</a>
                                <a href="http://www.lincolnpestcontrol.com" class="info" target="_blank">View Website</a>
                            </div>
                        </div>
                        </div>
                        <div class="container">
                        <div class="view">
                            <img src="images/france_s.jpg" alt="" />
                            <div class="mask">
                                <h2>France Sales and Service</h2>
                                <a href="images/france.jpg" class="info group1" data-fancybox-group="gallery">View Design</a>
                            </div>
                        </div>
                        </div>
                        <div class="container">
                        <div class="view">
                            <img src="images/spalding_s.jpg" alt="" />
                            <div class="mask">
                                <h2>Spalding Auto Parts</h2>
                                <a href="images/spalding.jpg" class="info group1" data-fancybox-group="gallery">View Design</a>
                                <a href="http://www.spaldings.com" class="info" target="_blank">View Website</a>
                            </div>
                        </div>
                        </div>
                        <div class="container">
                        <div class="view">
                            <img src="images/hub_s.jpg" alt="" />
                            <div class="mask">
                                <h2>Hub Home Improvements</h2>
                                <a href="images/hub.jpg" class="info group1" data-fancybox-group="gallery">View Design</a>
                                <a href="http://www.hubhomes.biz" class="info" target="_blank">View Website</a>
                            </div>
                        </div>
                        </div>
                        <div class="container">
                        <div class="view">
                            <img src="images/cardinal_s.jpg" alt="" />
                            <div class="mask">
                                <h2>Cardinal HVAC</h2>
                                <a href="images/cardinal.jpg" class="info group1" data-fancybox-group="gallery">View Design</a>
                                <a href="http://www.cardinalhvac.com" class="info" target="_blank">View Website</a>
                            </div>
                        </div>
                        </div>
                        <div class="container">
                        <div class="view">
                            <img src="images/historic_s.jpg" alt="" />
                            <div class="mask">
                                <h2>Historic Triangle Dentistry</h2>
                                <a href="images/historic.jpg" class="info group1" data-fancybox-group="gallery">View Design</a>
                                <a href="http://www.historictriangledentistry.com" class="info" target="_blank">View Website</a>
                            </div>
                        </div>
                        </div>
                        <div class="container">
                        <div class="view">
                            <img src="images/indie_s.jpg" alt="" />
                            <div class="mask">
                                <h2>Industrial Shoe Company</h2>
                                <a href="images/indie.jpg" class="info group1" data-fancybox-group="gallery">View Design</a>
                                <a href="http://www.industrialshoecompany.com" class="info" target="_blank">View Website</a>
                            </div>
                        </div>
                        </div>
                        <div class="container">
                        <div class="view">
                            <img src="images/sherry_s.jpg" alt="" />
                            <div class="mask">
                                <h2>Sherry Construction Corp.</h2>
                                <a href="images/sherry.jpg" class="info group1" data-fancybox-group="gallery">View Design</a>
                            </div>
                        </div>
                        </div>
                </div>
            </div>
            
            <div class="contact">
            	<div class="content">
                	<h2>Contact</h2>
                    <form method="post" id="myform" action="<?php echo htmlentities($_SERVER['PHP_SELF']); ?>"> 
                    <fieldset>
                    <p>
                    <label class="align">First Name: </label>
                    <label class="align">Last Name: </label>
                    </p>
                    <p>
                    <input type="text" name="fname" class="align" value='<?php echo htmlentities($fname) ?>' />
                    <input type="text" name="lname" class="align" value='<?php echo htmlentities($lname) ?>' />
                    </p>
                    <p>
                    <label class="align">Email: </label>
                    <label class="align">Phone: </label>
                    </p>
                    <p>
                    <input type="text" name="email" class="align" value='<?php echo htmlentities($email) ?>' />
                    <input type="text" name="phone" class="align" value='<?php echo htmlentities($phone) ?>' />
                    </p>
                    <p>
                    <label for='message'>Message:</label>
                    </p>
                    <p>
                    <textarea name="message" rows="4" cols="30" class="message" ><?php echo htmlentities($message) ?></textarea>
                    </p>
                    <input type="submit" value="SUBMIT" name='submit' id="submit" />
                    </fieldset>
                    </form>
                    <script language="JavaScript" type="text/javascript"  xml:space="preserve">//<![CDATA[
                    //You should create the validator only after the definition of the HTML form
                      var frmvalidator  = new Validator("myform");
					  

                     frmvalidator.addValidation("fname","req","Please enter your first name.");
                     frmvalidator.addValidation("fname","alpha_s","Please remove any numbers or special characters from your name. Thanks!");
                     frmvalidator.addValidation("lname","alpha_s","Please remove any numbers or special characters from your name. Thanks!");
                     
                      frmvalidator.addValidation("email","maxlen=50", "That email address is pretty long; are you sure you've got it right?");
                      frmvalidator.addValidation("email","req","Let's stay in touch! Please enter your email address to continue.");
                      frmvalidator.addValidation("email","email","Something went wrong with your email address. Make sure you've got your '@'s and your '.'s in the right place!");
                      
                      frmvalidator.addValidation("phone","maxlen=25","Your phone number is way too long to be valid.");
                      
                      frmvalidator.addValidation("message","req","Let me know your thoughts - please enter a brief message.");
                    
                    
                    //]]></script>
                </div>
            </div>
            
            <div class="thanks">
            	<div class="content">
                	<h2>Thanks</h2>
                    
                </div>
            </div>
            
        </div>
        
		
                
        <ul id="social">
            <li><a href="http://www.facebook.com/analucciadesign">Facebook</a></li>
            <li><a href="http://www.linkedin.com/pub/briana-de-luccia/38/231/126" target="_blank">LinkedIn</a></li>
        </ul>
	</div>
 
</body>
</html>
